<ScreenStart>:
    md_bg_color: app.theme_cls.backgroundColor
    container_box: box

    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:

                MDActionTopAppBarButton:
                    icon: "arrow-left"

            MDTopAppBarTitle:
                text: root.title_name
                pos_hint: {"center_x": 0.5}

            MDTopAppBarTrailingButtonContainer:

                MDActionTopAppBarButton:
                    icon: "pencil"

        MDScrollView:
            do_scroll_x: False

            MDBoxLayout:
                id: box
                orientation: "vertical"
                adaptive_height: True
                spacing: 20
                padding: 20


<Box>:
    adaptive_height: True


<BoxFormula>:
    orientation: "vertical"
    adaptive_height: True

    MDTextField:


<MiniBox>:
    orientation: "vertical"
    adaptive_height: True
    spacing: 30
    padding: 0, 5

    MDAnchorLayout:

        MDButton:
            id: button

    MDTextField:


