<Screen9@Screen>:
    name: "Статистика"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5

        BoxLayout:
            ButtonBack:
            ButtonToGuide:
                text: "Статистика guide"
        MyTextInput:
            hint_text: "x"
            filt: {*"0123456789., "}
            id: id_st_0
        MyTextInput:
            hint_text: "y"
            filt: {*"0123456789., "}
            id: id_st_1
        MyTextInput2:
            hint_text: "Результат"
            id: id_st_2
        Button:
            text: "calc"
            on_press: app.calc4((id_st_0.text, id_st_1.text), id_st_2)
