<ScreenSettings@MDScreen>:
    name: "Настройки"

    BoxLayoutPreset:

        MDBoxLayout:
            adaptive_height: True

            MDLabel:
                adaptive_width: True
                text: "Режим разработчика: "

            NormalChip:
                type: "filter"
                on_active: app.dev = args[1]

                MDChipText:
                    text: "Debug mode"

            MDWidget:

        MDBoxLayout:
            adaptive_height: True

            MDLabel:
                adaptive_width: True
                text: "Доверительный интервал: "

            NormalChip:
                type: "filter"
                on_active:
                    app.interval = 1 if args[1] else app.interval
                    if args[1]: self.uncheck_chip()

                MDChipText:
                    text: "90%"

            NormalChip:
                type: "filter"
                active: True
                on_active:
                    app.interval = 2 if args[1] else app.interval
                    if args[1]: self.uncheck_chip()

                MDChipText:
                    text: "95%"

            NormalChip:
                type: "filter"
                on_active:
                    app.interval = 3 if args[1] else app.interval
                    if args[1]: self.uncheck_chip()

                MDChipText:
                    text: "99%"
            MDWidget:

        MDWidget:
