<Screen1@Screen>:
    name: "Home"

    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5

        ButtonForward:
            text: "Настройки"
        ButtonForward:
            text: "Прямые измерения"
        ButtonForward:
            text: "МНК"
        ButtonForward:
            text: "Неравноточные измерения"
        ButtonForward:
            text: "Статистика"
        ButtonForward:
            text: "Косвенные измерения"
        ButtonForward:
            text: "Формулы exe"
