<ScreenSettings@MDScreen>:
    name: "Настройки"

    BoxLayoutPreset:

        MDBoxLayout:

            MDLabel:
                text: "Debug mode"

            MyToggleButton:
                text: "OFF"
                text_down: "ON"
                text_normal: "OFF"
                on_state: app.dev = True if args[1] == "down" else False

        MDBoxLayout:

            MDLabel:
                text: "Доверительный интервал"

            MDBoxLayout:
                spacing: 5

                ToggleButton:
                    group: "interval"
                    text: "90%"
                    on_state: app.interval = 1 if args[1] == "down" else app.interval

                ToggleButton:
                    group: "interval"
                    text: "95%"
                    state: "down"
                    on_state: app.interval = 2 if args[1] == "down" else app.interval

                ToggleButton:
                    group: "interval"
                    text: "99%"
                    on_state: app.interval = 3 if args[1] == "down" else app.interval
