<Screen4@Screen>:
    name: "Прямые измерения guide"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5
        Button:
            text: "Назад"
            size_hint: (1, 0.2)
            on_press:
                app.root.current = app.last
        MyLabel:
            text: "Прямые измерения - это n раз меришь одно значение.\n\nДанные - экспериментальные данные через пробел.\nНапример: '1.1 1.2 1.0' или '1,1 1,2 1,0'.\n\nТочность прибора.\nНапример: '0.1' или '0,1.\n\nРезультат - средние значение и дельта.\n\nslp - случайная погрешность\nprp - приборная погрешность\nobp - абсолютная погрешность\n"
