<Screen3@Screen>:
    name: "Прямые измерения"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5
        BoxLayout:
            Button:
                text: "Home"
                on_press:
                    app.root.current = self.text
            Button:
                text: "Прямые измерения guide"
                on_press:
                    app.last = self.parent.parent.parent.name
                    app.root.current = self.text

        MyTextInput:
            hint_text: "Данные"
            filt: {*"0123456789., "}
            id: id_pz_0
        MyTextInput:
            hint_text: "Точность прибора"
            filt: {*"0123456789.,"}
            id: id_pz_1
        MyTextInput2:
            hint_text: "Результат"
            id: id_pz_2
        Button:
            text: "calc"
            on_press: app.calc1((id_pz_0.text, id_pz_1.text), id_pz_2)
