<ScreenHome@MDScreen>:
    name: "Home"

    MDScrollView:
        do_scroll_x: False

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            padding: (50, 20)
            spacing: 5

            ButtonForwardList:
                text: "Настройки"
            ButtonForwardList:
                text: "Прямые измерения"
            ButtonForwardList:
                text: "МНК"
            ButtonForwardList:
                text: "Неравноточные измерения"
            ButtonForwardList:
                text: "Статистика"
            ButtonForwardList:
                text: "Косвенные измерения"
            ButtonForwardList:
                text: "Формулы exe"
