<Screen5@Screen>:
    name: "МНК"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5

        BoxLayout:
            Button:
                text: "Home"
                on_press:
                    app.root.current = self.text
            Button:
                text: "МНК guide"
                on_press:
                    app.last = self.parent.parent.parent.name
                    app.root.current = self.text
        MyTextInput:
            hint_text: "x"
            filt: {*"0123456789., "}
            id: id_mnk_0
        MyTextInput:
            hint_text: "y"
            filt: {*"0123456789., "}
            id: id_mnk_1

        GridLayout:
            cols: 2
            Label:
                text: "y = ax + b"
            Label:
                text: "y = ax"
            CheckBox:
                group: "МНК"
                active: True
                on_active:
                    app.cc1 = 1 if args[1] else app.cc1
            CheckBox:
                group: "МНК"
                on_active:
                    app.cc1 = 2 if args[1] else app.cc1
        MyTextInput2:
            hint_text: "Результат"
            id: id_mnk_2
        Button:
            text: "calc"
            on_press: app.calc2((id_mnk_0.text, id_mnk_1.text), app.cc1, id_mnk_2)
