<Screen1@Screen>:
    name: "Home"

    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5

        Button:
            text: "Настройки"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "Прямые измерения"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "МНК"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "Неравноточные измерения"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "Статистика"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "Косвенные измерения"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
        Button:
            text: "Формулы exe"
            on_press:
                root.manager.transition.direction = "left"
                root.manager.current = self.text
