<Screen6@Screen>:
    name: "МНК guide"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5
        Button:
            text: "Назад"
            size_hint: (1, 0.2)
            on_press:
                app.root.current = app.last
        MyLabel:
            text: "МНК - это метод наименьших квадратов, позволяющий находить коэффициенты (линейной) функции в зависимости Y от X.\n\nx и y - экспериментальные данные через пробел.\nНапример: '1.1 1.2 1.0' или '1,1 1,2 1,0'.\n\nРезультат - коэффициент корреляции, коэффициенты 'a' 'b' и их дельта."
