<Screen5@MDScreen>:
    name: "Косвенные измерения"

    BoxLayoutPresetWithGuide:

        MyTextInput:
            hint_text: "Формула"
            id: id_cs_0

        MyTextInput:
            hint_text: "Значения"
            id: id_cs_1

        MyTextInput2:
            hint_text: "Результат"
            id: id_cs_2

        Button:
            text: "calc"
            on_press: app.calc5((id_cs_0.text, id_cs_1.text), id_cs_2)
