<Screen8@Screen>:
    name: "Неравноточные измерения guide"
    BoxLayout:
        orientation: "vertical"
        padding: (50, 20)
        spacing: 5
        Button:
            text: "Назад"
            size_hint: (1, 0.2)
            on_press:
                app.root.current = app.last
        MyLabel:
            text: open("program/text/Неравноточные измерения guide.txt", encoding="utf-8").read()
