<Screen2@MDScreen>:
    name: "МНК"

    BoxLayoutPresetWithGuide:

        MDTextField:
            id: id_mnk_0

            MDTextFieldHintText:
                text: "x"

        MDTextField:
            id: id_mnk_1

            MDTextFieldHintText:
                text: "y"

        MDGridLayout:
            cols: 2

            MDLabel:
                halign: 'center'
                text: "y = ax + b"

            MDLabel:
                halign: 'center'
                text: "y = ax"

            MDAnchorLayout:

                MDCheckbox:
                    group: "МНК"
                    active: True
                    on_active: app.cc1 = 1 if args[1] else app.cc1

            MDAnchorLayout:

                MDCheckbox:
                    group: "МНК"
                    on_active: app.cc1 = 2 if args[1] else app.cc1

        MDTextField:
            id: id_mnk_2
            multiline: True
            mode: "filled"

            MDTextFieldHelperText:
                mode: "persistent"
                text: "Результат"

        MDButton:
            pos_hint: {"center_x": 0.5}
            on_release: app.calc2((id_mnk_0.text, id_mnk_1.text), app.cc1, id_mnk_2)

            MDButtonText:
                text: "calc"

        MDWidget:
