<Screen3@MDScreen>:
    name: "Неравноточные измерения"

    BoxLayoutPresetWithGuide:

        MyTextInput:
            hint_text: "Среднее значения"
            filt: {*"0123456789., "}
            id: id_nr_0

        MyTextInput:
            hint_text: "Погрешность значений"
            filt: {*"0123456789., "}
            id: id_nr_1

        MyTextInput2:
            hint_text: "Результат"
            id: id_nr_2

        Button:
            text: "calc"
            on_press: app.calc3((id_nr_0.text, id_nr_1.text), id_nr_2)
