<Screen3@MDScreen>:
    name: "Неравноточные измерения"

    BoxLayoutPresetWithGuide:

        MDTextField:
            id: id_nr_0

            MDTextFieldHintText:
                text: "Среднее значения"

        MDTextField:
            id: id_nr_1

            MDTextFieldHintText:
                text: "Погрешность значений"

        MDTextField:
            id: id_nr_2
            multiline: True
            mode: "filled"

            MDTextFieldHelperText:
                mode: "persistent"
                text: "Результат"

        MDButton:
            pos_hint: {"center_x": 0.5}
            on_release: app.calc3((id_nr_0.text, id_nr_1.text), id_nr_2)

            MDButtonText:
                text: "calc"

        MDWidget:
