<Screen6@MDScreen>:
    name: "Формулы exe"

    BoxLayoutPresetWithGuide:

        MDTextField:
            id: id_fe_0

            MDTextFieldHintText:
                text: "Формула"

        MDTextField:
            id: id_fe_1

            MDTextFieldHintText:
                text: "Значения"

        MDTextField:
            id: id_fe_2
            multiline: True
            mode: "filled"

            MDTextFieldHelperText:
                mode: "persistent"
                text: "Результат"

        MDButton:
            pos_hint: {"center_x": 0.5}
            on_release: app.calc6((id_fe_0.text, id_fe_1.text), id_fe_2)

            MDButtonText:
                text: "calc"

        MDWidget:
