<Screen1@MDScreen>:
    name: "Прямые измерения"

    BoxLayoutPresetWithGuide:

        MyTextInput:
            hint_text: "Данные"
            filt: {*"0123456789., "}
            id: id_pz_0

        MyTextInput:
            hint_text: "Точность прибора"
            filt: {*"0123456789.,"}
            id: id_pz_1

        MyTextInput2:
            hint_text: "Результат"
            id: id_pz_2

        Button:
            text: "calc"
            on_press: app.calc1((id_pz_0.text, id_pz_1.text), id_pz_2)
