<Screen5@MDScreen>:
    name: "Косвенные измерения"

    BoxLayoutPresetWithGuide:

        MDTextField:
            id: id_cs_0

            MDTextFieldHintText:
                text: "Формула"

        MDTextField:
            id: id_cs_1

            MDTextFieldHintText:
                text: "Значения"

        MDTextField:
            id: id_cs_2
            multiline: True
            mode: "filled"

            MDTextFieldHelperText:
                mode: "persistent"
                text: "Результат"

        MDButton:
            pos_hint: {"center_x": 0.5}
            on_release: app.calc5((id_cs_0.text, id_cs_1.text), id_cs_2)

            MDButtonText:
                text: "calc"

        MDWidget:
