<Screen4@MDScreen>:
    name: "Статистика"

    BoxLayoutPresetWithGuide:

        MDTextField:
            id: id_st_0
            MDTextFieldHintText:
                text: "x"

        MDTextField:
            id: id_st_1

            MDTextFieldHintText:
                text: "y"

        MDTextField:
            id: id_st_2
            multiline: True
            mode: "filled"

            MDTextFieldHelperText:
                mode: "persistent"
                text: "Результат"

        MDButton:
            pos_hint: {"center_x": 0.5}
            on_release: app.calc4((id_st_0.text, id_st_1.text), id_st_2)

            MDButtonText:
                text: "calc"

        MDWidget:
