#:include program/components/screen_home.kv
#:include program/components/screen_settings.kv
#:include program/components/screen3.kv
#:include program/components/screen5.kv
#:include program/components/screen7.kv
#:include program/components/screen9.kv
#:include program/components/screen11.kv
#:include program/components/screen13.kv

#:include program/components/my_buttons.kv
#:include program/components/screen_guide.kv

<MyLabel@Label>:
    text_size: [None, None]
    text_size: self.size
    valign: "center"
    halign: "center"


MDScreenManager:
    md_bg_color: app.theme_cls.backgroundColor

    ScreenHome:
    ScreenSettings:
    Screen3:
    Screen5:
    Screen7:
    Screen9:
    Screen11:
    Screen13:

    ScreenGuide:
