#:include program/components/my_buttons.kv
#:include program/components/screen_guide.kv

#:include program/components/screen_home.kv
#:include program/components/screen_settings.kv

#:include program/components/screen1.kv
#:include program/components/screen2.kv
#:include program/components/screen3.kv
#:include program/components/screen4.kv
#:include program/components/screen5.kv
#:include program/components/screen6.kv

#:include program/components/screen_test.kv


MDScreenManager:
    md_bg_color: app.theme_cls.backgroundColor

    ScreenHome:
    ScreenSettings:

    Screen1:
    Screen2:
    Screen3:
    Screen4:
    Screen5:
    Screen6:

    ScreenGuide:
    ScreenTest:
